"""Combined post-training risk, regime/concentration diagnostics and report evidence."""
from pathlib import Path
import json,hashlib
from datetime import datetime,timezone
import numpy as np
import pandas as pd
from systematic_research.execution_stress import minute_outcomes,schedule_events,marked_drawdowns
from systematic_research.trade_report_metrics import trade_kpis

L=Path('saved_strategies/NQ_RTH_100_LOCKED_20261007');O=L/'FULL_VALIDATION_20261007';P=Path('data/processed/nq_entry_discovery_202210')
protocol=json.loads((O/'PROTOCOL.json').read_text());short=json.loads((L/'LOCKED_ENTRIES.json').read_text());verdict=pd.read_csv(O/'candidate_verdicts.csv');survivors=set(verdict[verdict.simulation_survivor].candidate)
m=pd.read_parquet(P/'minutes.parquet');f=pd.read_parquet(P/'opportunities.parquet');bits=np.load(P/'atom_bits.npy',mmap_mode='r');schedule=pd.read_parquet(P/'rth_schedule.parquet')
clock=m.index.asi8;ohlc=m[['open','high','low','close']].to_numpy(float);starts=f.index.asi8;ends=pd.DatetimeIndex(f.planned_exit).asi8;targets=(f.entry_open+f.target_points).to_numpy(float)
post=f.split.isin(['validation','final_confirmation']).to_numpy();sessions=pd.DatetimeIndex(f.loc[post,'anchor'].unique()).sort_values();signals=[]
for item in short:
 a=[q['atom_id'] for q in item['definition']];words=bits[a[0]]&bits[a[1]]&bits[a[2]];signals.append(np.unpackbits(words.view(np.uint8),bitorder='little')[:len(f)].astype(bool))
outcomes={name:minute_outcomes(clock,ohlc,starts,ends,targets,*args) for name,args in protocol['scenarios'].items()}
daily=[]
for _,s in schedule.iterrows():
 path=m[(m.index>=s.open)&(m.index<s.close)];daily.append({'anchor':s.open,'close':path.close.iloc[-1],'range':path.high.max()-path.low.min()})
d=pd.DataFrame(daily).set_index('anchor');d['prior_20session_return']=d.close.shift(1)/d.close.shift(21)-1;d['past_range20']=d.range.shift(1).rolling(20).mean();cut=d.loc[d.index.year<=2024,'past_range20'].median();d['regime']=np.where(d.prior_20session_return>=0,'prior20_up','prior20_down');d['volatility']=np.where(d.past_range20>cut,'past_range_above_IS_median','past_range_below_IS_median')
metrics=[];curves=[];regimes=[];concentration=[]
for k,item in enumerate(short):
 cid=item['id']
 for name,args in protocol['scenarios'].items():
  a=outcomes[name];chosen=schedule_events(signals[k]&post,starts,a);t=f.iloc[chosen][['anchor','target_points','planned_exit']].copy();t['entry_time']=f.index[chosen]+pd.Timedelta(minutes=args[0]);t['entry_price']=a[chosen,4];t['exit_price']=a[chosen,5];t['exit_time']=pd.to_datetime(a[chosen,0].astype(np.int64),utc=True);t['net_dollars']=a[chosen,1];t['status']=np.where(a[chosen,3]==0,'unresolved',np.where(a[chosen,2]==1,'target','timeout'));t['mae_upper_points']=a[chosen,6];t['holding_minutes']=a[chosen,8]
  kp,curve=trade_kpis(t,sessions);dd,lowdd=marked_drawdowns(clock,ohlc,starts,a,chosen,args[0],args[1]);kp.update({'candidate':cid,'period':'post_training_combined','variant':name,'minute_close_dd':dd,'minute_low_dd_bound':lowdd});metrics.append(kp)
  if name in ['base','combined_stress']:
   curve['candidate']=cid;curve['variant']=name;curve['net_profit_cumulative']=curve.balance-100000;curve['date']=curve.index.tz_convert('America/New_York').strftime('%Y-%m-%d');curves.extend(curve.reset_index(drop=True).to_dict('records'));curve.to_csv(O/f'{cid}_{name}_combined_daily.csv',index_label='cash_session_open')
   if cid in survivors:t.to_csv(O/f'{cid}_{name}_combined_trades.csv',index=False)
  if name=='base':
   t['regime']=d.regime.reindex(pd.DatetimeIndex(t.anchor)).to_numpy();t['volatility']=d.volatility.reindex(pd.DatetimeIndex(t.anchor)).to_numpy()
   for field in ['regime','volatility']:
    for label,g in t.groupby(field):
     loss=-g.net_dollars[g.net_dollars<0].sum();regimes.append({'candidate':cid,'cut':field,'regime':label,'trades':len(g),'net_profit':g.net_dollars.sum(),'profit_factor':g.net_dollars[g.net_dollars>0].sum()/loss if loss>0 else np.nan,'net_win_rate':g.net_dollars.gt(0).mean()})
   top=t.net_dollars.nlargest(5).sum();concentration.append({'candidate':cid,'net_profit':t.net_dollars.sum(),'net_after_removing_top5_trades':t.net_dollars.sum()-top,'top5_winners_share_of_gross_wins':top/t.net_dollars[t.net_dollars>0].sum()})
 print('COMBINED',cid,flush=True)
metric=pd.DataFrame(metrics);metric.to_csv(O/'combined_execution_metrics.csv',index=False);pd.DataFrame(regimes).to_csv(O/'regime_results.csv',index=False);pd.DataFrame(concentration).to_csv(O/'profit_concentration.csv',index=False)
pd.DataFrame(curves).to_json(O/'combined_curves.json',orient='records')
allmetrics=pd.concat([pd.read_csv(O/'all_execution_metrics.csv'),metric],ignore_index=True);allmetrics.to_csv(O/'all_periods_execution_metrics.csv',index=False)
base=metric[metric.variant.eq('base')];summary=verdict.merge(base[['candidate','trades','net_profit','profit_factor','net_win_rate','sharpe','minute_close_dd','minute_low_dd_bound','worst_trade','mean_mae_points']],on='candidate').merge(pd.DataFrame(concentration).drop(columns='net_profit'),on='candidate');summary['failure_reasons']=summary.failure_reasons.fillna('Passed declared simulation gates');summary.to_csv(O/'candidate_comparison.csv',index=False)
st=pd.read_csv(O/'statistical_diagnostics.csv');quarter=pd.read_csv(O/'quarterly_results.csv');audit=json.loads((O/'DATA_AUDIT.json').read_text());prefix=json.loads((O/'FEATURE_PREFIX_VERIFICATION.json').read_text());execution=json.loads((O/'EXECUTION_VERIFICATION.json').read_text())
best=summary[summary.simulation_survivor&summary.group_representative].sort_values('min_post_stress_pf',ascending=False).iloc[0];focus=summary[summary.candidate.eq('NQ_000926441771')].iloc[0]
def records(df):return json.loads(df.to_json(orient='records'))
def source(label,files,ids,definition):return {'label':label,'files':[str((O/p).resolve()) for p in files],'evidenceFlow':[{'title':'Frozen-rule forward execution','detail':'Original100 entry rules, exact138 atom thresholds reconciled;2022–2024 discovery,2025 previously used validation,2026 previously seen separate replay. All observations advance chronologically; one position per candidate. No live feed or orders.'},{'title':'Independent execution verification','detail':'All300 original base candidate-period KPI sets matched archived results. Six candidate/scenario cases match an independent slow minute engine. Two truncated-history spot checks reproduce all66 required features.'}],'metricDefinitions':[{'label':label,'definition':definition,'componentIds':ids}]}
snapshot={'surface':'report','title':'13 NQ entry rules survive tougher historical execution tests','generatedAt':datetime.now(timezone.utc).isoformat(),'status':'reviewed','buildStatus':'creating','report':{'asOf':'2026-08-20'},'filters':[],'defaultCandidate':str(best.candidate),'queries':{
 'verdicts':{'rows':records(summary),'source':source('All100 frozen candidate decisions',['candidate_comparison.csv','PROTOCOL.json'],['candidate-comparison'],'Simulation survivor means all six predeclared post-2024 execution/support/quarter/bootstrap/placebo gates passed. No daily entry requirement. Minimum stress PF and net PNL are minima over9 scenarios separately in2025 and2026; not a portfolio or a quarter minimum. Combined base metrics cover2025 and2026.')},
 'metrics':{'rows':records(allmetrics),'source':source('Minute-forward execution metrics',['all_periods_execution_metrics.csv','PROTOCOL.json'],['metrics-cards-0','metrics-cards-1','metrics-cards-2','metrics-cards-3','stress-table','period-table'],'One NQ contract, base$25 round trip; documented delay/slippage/penetration scenarios. Trade PF=sum positive net trade PNL / abs(sum negative net trade PNL); net win%=share of resolved positive trades; Sharpe=mean daily account return/sample SD*sqrt252, rf0, $100k reference, inactive cash sessions included. Minute close DD marks every held minute; minute low is a conservative OHLC order bound.')},
 'quarters':{'rows':records(quarter[quarter.period.ne('in_sample')]),'source':source('Post-2024 chronological quarter results',['quarterly_results.csv'],['quarter-table'],'Quarter blocks of frozen rules, without parameter retuning.2026Q3 endsAugust20 and is partial. Earlier candidate selection used2025 and saw2026; these are chronological replays, not fresh blind walk-forward discovery.')},
 'curves':{'rows':curves,'source':source('2025–2026 daily account marks',['combined_curves.json'],['equity-chart','drawdown-chart'],'Daily cash-session realized PNL cumulative; all intraday original positions exit before cash close. Base and combined execution stress curves use the same entry rules; delayed trades can suppress or skip entries. Drawdown plotted as negative percent from daily account peak; actual minute risk shown separately.')},
 'regimes':{'rows':records(pd.DataFrame(regimes)),'source':source('Causal regime diagnostics',['regime_results.csv'],['regime-table'],'Trend labels compare previous completed cash-session close with21-sessions-ago close; range labels use prior20 complete cash-session ranges and a median threshold fitted through2024. Labels use no current-session outcome.')},
 'statistics':{'rows':records(st),'source':source('Dependence and timing placebo diagnostics',['statistical_diagnostics.csv','PROTOCOL.json'],['statistics-table'],'2000 circular five-session block bootstraps include inactive days.2000 eligible-entry timing placebos preserve raw signal counts by year, weekday and clock slot, then obey nonoverlap execution. Raw p compares trade expectancy. Holm correction is for100 shortlisted comparisons only, not the ten-million-definition discovery. Descriptive selected-history diagnostics, not independent edge probabilities.')}
 },'audit':audit,'featureVerification':prefix,'executionVerification':execution,'requirements':{'minimum_one_entry_per_session':False,'simulation_only':True},'research_sources':['https://www.davidhbailey.com/dhbpapers/deflated-sharpe.pdf']}
(O/'report_snapshot.json').write_text(json.dumps(snapshot,allow_nan=False))
lines=['# Historical forward simulation of the100 frozen NQ entries','', '**13 rules survived, spanning10 similarity groups;10 are preselected group representatives.** The daily-entry requirement is removed. This simulates historical execution; it has not traded a live or paper account.','',
'## What passed','', 'Each survivor has sufficient trade support, positive PNL/PF≥1.10 across9 execution scenarios in both2025 and2026, positive supported calendar quarters, a positive five-session bootstrap lower mean bound, and better expectancy than same-clock/weekday/year eligible random-entry timing. Holm100 diagnostic also passes for these13. These tests do not correct the original ten-million-rule search or make previously seen history a blind holdout.','',
'| Representative | Combined2025–2026 base profit | Base PF | Net win | Worst period/scenario PF | Worst period/scenario profit |','|---|---:|---:|---:|---:|---:|']
for _,r in summary[summary.simulation_survivor&summary.group_representative].sort_values('min_post_stress_pf',ascending=False).iterrows():lines.append(f'| {r.candidate} | ${r.net_profit:,.0f} | {r.profit_factor:.2f} | {r.net_win_rate:.1%} | {r.min_post_stress_pf:.2f} | ${r.min_post_stress_net_profit:,.0f} |')
lines+=['','## Previously highlighted rule','', 'NQ_000926441771 fails the execution-robustness gate.2025 base PNL+$92,995 becomes−$16,295 at two-minute delay (PF0.86), and−$7,735 under combined stress. Its2026 base performance does not override the earlier fragility.','',
'## Scope and limits','',f'2700 period/scenario replays plus900 combined diagnostics,1600 quarter records,200k randomized timing simulations and2000 shared weekly block bootstraps. All300 original base KPI sets reconciled; six independent slow-engine cases and two prefix checks passed. One of967 scheduled cash sessions has one missing minute; none of the selected stress paths became unresolved.','',
'The alternate NQ dataset is the same export, not independent vendor evidence. Per-contract volume-roll history and exporter timestamp semantics remain unverified. Minute data cannot establish actual bid/ask spread, queue priority, latency or stop-fill behavior. Limit penetration and delays are explicit stress assumptions, not observed fills. Session holidays use the cash-session calendar; extended Globex/ML exits remain separate preliminary research. No hard stop or sizing/margin model is added. Similarity groups use80% signal Jaccard connected components and do not imply independent economic ideas.','',
'The source endsAugust20,2026. All post-2024 history was previously used. Thus these13 are simulation survivors for further research, not institutionally certified systems. The10 group representatives were selected using validation worst-scenario PF before the current final gate, without2026 re-ranking.','',
'[Deflated Sharpe research](https://www.davidhbailey.com/dhbpapers/deflated-sharpe.pdf) explains why prior search breadth matters. Full-search DSR/PBO is not claimed here because the complete10-million-trial return histories/Sharpe dispersion are not supplied to this test. All100 rules remain saved; rejected rules and exact reasons are retained.']
(O/'RESULTS.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('BEST REPRESENTATIVE',str(best.candidate));print(summary[summary.simulation_survivor&summary.group_representative][['candidate','net_profit','profit_factor','net_win_rate','min_post_stress_pf']].sort_values('min_post_stress_pf',ascending=False).to_string(index=False))
