"""Source-backed dual-clock comparison; preserve the new app's stable identity."""
from pathlib import Path
import json
from datetime import datetime,timezone
import pandas as pd

O=Path('saved_strategies/NQ_RTH_100_LOCKED_20261007/FULL_VALIDATION_20261007');E=O/'MINUTE_END_SCENARIO';A=Path('work/nq_long_ml/full_validation_report_app')
s=json.loads((A/'src/data.json').read_text(encoding='utf-8'));s['title']='NQ simulation: one research lead after timestamp stress';s['generatedAt']=datetime.now(timezone.utc).isoformat();s['clockCases']=['original','minute_end'];s['defaultCase']='minute_end'
old=pd.read_csv(O/'candidate_verdicts.csv');new=pd.read_csv(E/'candidate_verdicts.csv');merged=old.merge(new,on='candidate',suffixes=('_original','_end'))
decision=pd.DataFrame({'candidate':merged.candidate,'passed_original':merged.simulation_survivor_original,'passed_minute_end':merged.simulation_survivor_end,'passed_both':merged.simulation_survivor_original&merged.simulation_survivor_end,'end_min_stress_pf':merged.min_post_stress_pf_end,'end_min_stress_profit':merged.min_post_stress_net_profit_end,'end_failure_reasons':merged.failure_reasons_end.fillna('Passed post-2024 gates')})
is_metrics=pd.read_csv(E/'all_execution_metrics.csv');all_year=is_metrics.groupby('candidate').agg(min_profit=('net_profit','min'),min_pf=('profit_factor','min'));decision['passed_all_periods_all_scenarios']=decision.candidate.map((all_year.min_profit>0)&(all_year.min_pf>=1.1))&decision.passed_both
decision.to_csv(O/'dual_clock_candidate_comparison.csv',index=False)
metric_keys=['candidate','period','variant','trades','net_profit','profit_factor','net_win_rate','target_hit_rate','sharpe','minute_close_dd','minute_low_dd_bound','mean_mae_points','worst_trade','session_coverage','unknown_trades']
metrics=[];quarters=[];curves=[];regimes=[];statistics=[]
for label,folder in [('original',O),('minute_end',E)]:
 m=pd.read_csv(folder/'all_periods_execution_metrics.csv');m=m[[k for k in metric_keys if k in m]].assign(timestamp_case=label);metrics.extend(json.loads(m.to_json(orient='records')))
 q=pd.read_csv(folder/'quarterly_results.csv');q=q[q.period.ne('in_sample')].assign(timestamp_case=label);quarters.extend(json.loads(q.to_json(orient='records')))
 c=pd.read_json(folder/'combined_curves.json');c=c[c.candidate.isin(['NQ_000748828115','NQ_000926441771'])];c['date']=pd.to_datetime(c.date).dt.strftime('%Y-%m-%d');c=c[['date','candidate','variant','pnl_dollars','net_profit_cumulative','drawdown_pct']].assign(timestamp_case=label);curves.extend(json.loads(c.to_json(orient='records')))
 r=pd.read_csv(folder/'regime_results.csv').assign(timestamp_case=label);regimes.extend(json.loads(r.to_json(orient='records')))
 st=pd.read_csv(folder/'statistical_diagnostics.csv').assign(timestamp_case=label);statistics.extend(json.loads(st.to_json(orient='records')))
s['queries']['metrics']['rows']=metrics;s['queries']['quarters']['rows']=quarters;s['queries']['curves']['rows']=curves;s['queries']['regimes']['rows']=regimes;s['queries']['statistics']['rows']=statistics
for query,file in [('metrics','all_periods_execution_metrics.csv'),('quarters','quarterly_results.csv'),('curves','combined_curves.json'),('regimes','regime_results.csv'),('statistics','statistical_diagnostics.csv')]:
 source=s['queries'][query]['source'];source['files']=[str((folder/file).resolve()) for folder in [O,E]];source['evidenceFlow']=[{'title':'Dual timestamp simulations','detail':'Original minute-start assumption and minute-end sensitivity (NQ timestamps minus1minute) evaluated separately. The latter matches6849 overlapping new5m bar shapes and volumes exactly under NewYork close-label interpretation. Original thresholds remain unchanged; endpoint human confirmation pending.'},{'title':'Execution verification','detail':'Original300 base KPI sets matched archived results. Six slow independent minute-engine cases passed in each clock case. Original feature prefix spot checks passed; shifted-clock feature/target data rebuilt causally using same formulas.'}]
 source['metricDefinitions'][0]['definition']+=' Timestamp_case identifies each separate simulation; results are never added across clock cases.'
s['queries']['curves']['source']['metricDefinitions'][0]['definition']+=' Daily PNL and drawdown are rebased to$100k for the selected year or combined period. Chart scope is survivor NQ_000748828115 and previously highlighted NQ_000926441771; other rules retain source logs and full KPIs.'
s['queries']['clock_decisions']={'rows':json.loads(decision.to_json(orient='records')),'source':{'label':'All100 dual-clock gate decisions','files':[str((O/'dual_clock_candidate_comparison.csv').resolve()),str((E/'PROTOCOL.json').resolve())],'evidenceFlow':[{'title':'Frozen inputs','detail':'All100 original definitions and exact numerical thresholds retained; no refitting after new import.13 provisional candidates were frozen before attachment read.'}],'metricDefinitions':[{'label':'Passed both clocks','definition':'Passed all six post-2024 predeclared support/execution/quarter/bootstrap/placebo gates separately under both clock interpretations. One rule passes. All-period all-scenario status additionally requires positivePNL andPF>=1.10 in discovery and each post-2024 period; none passes that stricter diagnostic.','componentIds':['candidate-comparison']}]}}
s['verification']={'tests_passed':181,'new_execution_tests':4,'scoped_lint_type_format':'Clean after final type annotations','full_baseline':'40 lint errors,89 type errors,6 formatting files pre-existed; no unrelated fixes','native_clock_verification':json.loads((E/'EXECUTION_VERIFICATION.json').read_text()),'original_base_verification':json.loads((O/'EXECUTION_VERIFICATION.json').read_text())};s['clockAssumptionPending']=True;s['all_period_all_scenario_survivors']=int(decision.passed_all_periods_all_scenarios.sum());s['newImportAudit']=json.loads((O/'NEW_IMPORT_AUDIT/AUDIT.json').read_text())
(A/'src/data.json').write_text(json.dumps(s,allow_nan=False),encoding='utf-8')
summary={'phase':'complete_for_available_historical_inputs','minimum_one_entry_per_session':False,'simulations':'Historical only; no live feed, paper account or orders','original_post_gate_survivors':int(decision.passed_original.sum()),'minute_end_post_gate_survivors':int(decision.passed_minute_end.sum()),'passed_both_clocks':decision[decision.passed_both].candidate.tolist(),'all_period_all_scenario_survivors':int(decision.passed_all_periods_all_scenarios.sum()),'limitations':'Endpoint confirmation pending;2025/2026 previously seen; original ten-million search not fully statistically corrected; per-contract volume-roll provenance unverified','new_import':'9402 clean5m rows,32 dates afterAugust20; exact new-date scoring lacks corresponding minute/fullsessionNQ and ES history','raw_data_preserved':True,'original_results_archived_and_qualified':True}
(O/'FINAL_STATUS.json').write_text(json.dumps(summary,indent=2))
lines=['# NQ simulation after the new-import timestamp audit','', '**One rule passes the declared post-2024 gates under both clock interpretations: NQ_000748828115. No rule passes the stricter all-period/all-scenario diagnostic.** One entry per session is no longer required. All100 original entry definitions and numerical thresholds remain frozen.','',
'The original minute-start assumption produced13 provisional post-2024 survivors. The new5m export matches6849 overlapping relativeOHLC shapes and volumes exactly after shifting old minute timestamps−1minute; matched prices differ by+297.25points. Under the corresponding minute-end sensitivity, only one passes the post-2024 gates. This qualifies earlier optimistic fill assumptions; human endpoint confirmation is still pending.','',
'| NQ_000748828115, minute-end assumption | Trades | Net profit | Trade PF | Net-winning trades |','|---|---:|---:|---:|---:|']
cm=pd.read_csv(E/'all_periods_execution_metrics.csv')
for period,label in [('in_sample','Discovery2022–2024'),('validation','Previously used2025'),('final_confirmation','Previously seen2026'),('post_training_combined','Combined2025–2026')]:
 r=cm[(cm.candidate=='NQ_000748828115')&(cm.period==period)&cm.variant.eq('base')].iloc[0];lines.append(f'| {label} | {int(r.trades)} | ${r.net_profit:,.0f} | {r.profit_factor:.2f} | {r.net_win_rate:.1%} |')
r=cm[(cm.candidate=='NQ_000748828115')&(cm.period=='post_training_combined')&cm.variant.eq('combined_stress')].iloc[0]
lines+=['',f'Combined delay/slippage/penetration/$50cost stress over2025–2026: ${r.net_profit:,.0f}, PF{r.profit_factor:.2f}, {r.net_win_rate:.1%} net winners. Base combined minute-close drawdown is$15,160. Discovery stress is weaker: $100round-trip costs yield−$5,980 and combined stress−$315, so this is a research lead, not an all-regime certified system.','',
'The prior highlightedNQ_000926441771 has minute-end base PNL−$95 in2025 and+$7,695 in2026. The original$101,4352026 figure belongs to the old clock case and is not the corrected-clock estimate.','',
'The new attachment is preserved, with9402 clean unique5m bars fromApril23 throughOctober7,2026. Three malformed rows are quarantined and86 identical repeats logged; no conflicting duplicates.32 dates follow the oldAugust20cutoff. We froze13 candidates before reading the new file. These dates are not scored as a fresh holdout because the attachment lacks minute/full-GlobexNQ and contemporaneousES needed to calculate the frozen signals and delayed fills. Missing features are not converted into zero trades.','',
'Scope: two clock cases×2700 period/scenario replays, plus1800 combined diagnostics,3200 quarter records,400k randomized timing trials and weekly block bootstrap checks. The9 fill/cost scenarios and gate definitions are saved inPROTOCOL.json. Independent minute-engine checks passed in both clock cases. Original138 atom thresholds reproduce packed masks exactly; two history-prefix spot checks reproduce66 required features.181 repository tests passed; scoped code checks pass; pre-existing repository lint/type/format issues remain.','',
'All historical post-2024 data were previously seen, and all100 definitions were selected after10milliontrials.100-comparisonHolm and weekly bootstrap diagnostics are retrospective and do not correct that full search. No full-searchDSR/PBO is claimed. Underlying volume-roll contract provenance remains unverified. MinuteOHLCcannot reproduce actualbidask, queueposition or trueintraminute ordering; penalties are assumptions. No stop, sizing or margin model is added. These are simulated historical outcomes, not live/paper execution.','',
'The new clock audit supersedes the earlier13-survivor conclusion. Old results are retained for reproducibility. Local source data and locked strategies were not deleted; generated redundant report data were reduced and generated files transparently compressed after thedrive filled.','',
'[Selection-bias research](https://www.davidhbailey.com/dhbpapers/deflated-sharpe.pdf) explains why search breadth and return distribution matter; it does not validate this survivor.']
(O/'FINAL_RESULTS.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps(summary,indent=2));print('APP_DATA_BYTES',(A/'src/data.json').stat().st_size)
